apiVersion: batch/v1
kind: Job
metadata:
  labels:
    {{- include "commonLabels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    {{- include "commonAnnotations" . | nindent 4 }}
  name: installplan-approver-job-{{ .Values.subscription.name }}
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:latest
          command:
            - /bin/bash
            - -c
            - |
              export subs={{ .Values.subscription.name }}
{{ .Files.Get "files/approver.sh" | indent 14 }}
          imagePullPolicy: Always
          name: installplan-approver
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: installplan-approver-job-{{ .Values.subscription.name }}
      serviceAccountName: installplan-approver-job-{{ .Values.subscription.name }}
      terminationGracePeriodSeconds: 30
