apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    {{- include "commonAnnotations" . | nindent 4 }}
