repoURL: https://github.com/digital-iq/gitops-demo-grafana-operator.git
app_name: helm-grafana-operator
helmChartName: grafana-operator
argoCDNamespace: infra-gitops

generatorsList:
- clusters:
    selector:
      matchLabels:
        env: 'dev'
        type: app
    values:
      operatorVersion: "grafana-operator.v5.15.1"
      tagRevision: "1.0.0"

- clusters:
    selector:
      matchLabels:
        env: 'stg'
        type: app
    values:
      operatorVersion: "grafana-operator.v5.14.0"
      tagRevision: "1.0.0"

- clusters:
    selector:
      matchLabels:
        env: 'prd'
        type: mgt
    values:
      operatorVersion: "grafana-operator.v5.14.0"
      tagRevision: "1.0.0"

revision: '{{ values.tagRevision }}'

valuesList:
  valuesObject:
    subscription:
      startingCSV: "{{ values.operatorVersion }}"

syncPolicyList:
  retry:
    limit: -1
  automated:
    prune: false
    selfHeal: true
  syncOptions:
  - ApplyOutOfSyncOnly=true
  - PruneLast=true
